/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.clientes.vista;

import co.unicauca.clientes.modelo.*;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author jhayber
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form GUIEstadisticaPorSexoGrafica
     */
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
        initComponents();
        setSize(400, 300);
        setLocation(h, v);
        setVisible(true);
    }

    private GUIEstadisticaPorSexoGrafica() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public void update(Observable obs, Object obj) {
        ClientesDB cliDB = (ClientesDB) obs;
        this.setTitle("Profesión: " + cliDB.getProfesion());
        graficar(cliDB.getTotalHombres(), cliDB.getTotalMujeres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablero = new javax.swing.JPanel();
        lbHombres = new javax.swing.JLabel();
        lbMujeres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableroLayout.createSequentialGroup()
                .addGap(0, 304, Short.MAX_VALUE)
                .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMujeres, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableroLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lbHombres)
                .addGap(26, 26, 26)
                .addComponent(lbMujeres)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        lbMujeres.getAccessibleContext().setAccessibleName("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstadisticaPorSexoGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstadisticaPorSexoGrafica().setVisible(true);
            }
        });
    }


    private void graficar(int totalHombres, int totalMujeres) {
        int total, valorHombres, valorMujeres, porHombres, porMujeres;
        total = totalHombres + totalMujeres;
        
        porHombres = ((totalHombres * 100)/total);
        porMujeres = ((totalMujeres * 100)/total);
        
        Graphics g = pnlTablero.getGraphics();
        
        
        g.setColor(Color.red);
        g.fillRect(5, 30, 30, 100);
        g.drawString("Hombres",0, 200);
        
        g.setColor(Color.white);
        g.fillRect(5, 30, 30, porHombres);
       
        
        g.setColor(Color.red);
        g.fillRect(70, 30, 30, 155);
        g.drawString("Mujeres",65, 200);
        
        g.setColor(Color.white);
        g.fillRect(70, 30, 30, porMujeres);
        
        
        /*
        total = totalHombres + totalMujeres;
        porHombres = ((totalHombres * 100)/total);
        valorHombres = ((totalHombres * 360)/total);
        porMujeres = ((totalMujeres * 100)/total);
        valorMujeres = ((totalMujeres * 360)/total);


        g.setColor(Color.red);
        g.fillArc(25, 50, 200, 200, 0, valorHombres);
        g.drawString("Hombres",240, 140);
        lbHombres.setText(porHombres + "%");
        
        g.setColor(Color.BLUE);
        g.fillArc(25, 50, 200, 200, valorHombres, valorMujeres);
        g.drawString("Mujeres",240, 180);
        lbMujeres.setText(porMujeres + "%");
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHombres;
    private javax.swing.JLabel lbMujeres;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
